[package]
name = "borrg"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
chrono = "0.4"
toml = "0.8"
dirs = "5.0"
serde_json = "1.0"
indicatif = "0.17"
thiserror = "1.0"
