[package]
name = "borrg"
version = "0.1.1"
edition = "2021"
license = "MIT"

[features]
default = ["borg1", "borg2"]
deprecated = []
borg1 = []
borg2 = []

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
toml = "0.8"
dirs = "6.0"
serde_json = "1.0"
indicatif = "0.17"
thiserror = "2.0"
smol_str = { version = "0.3", default-features = false, features = ["std"] }
